# Generated by Django 3.2.2 on 2021-08-18 03:40

from django.db import migrations, models
import django.db.models.deletion
import imgAPI.models


class Migration(migrations.Migration):

    dependencies = [
        ('imgAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sm_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='post_image',
            name='picture',
            field=models.ImageField(blank=True, upload_to=imgAPI.models.post_image.make_path),
        ),
        migrations.CreateModel(
            name='sm_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1024)),
                ('status', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('image_dir', models.CharField(max_length=255)),
                ('is_share_with_customer', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgAPI.sm_user')),
                ('photographer_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photographer_owner', to='imgAPI.sm_user')),
            ],
        ),
        migrations.CreateModel(
            name='event_mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgAPI.sm_event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgAPI.sm_user')),
            ],
        ),
    ]
