# Generated by Django 3.2.2 on 2021-05-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='post_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, upload_to='selected_pic')),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
